name: Build and Push Docker Image

on:
  push:
    tags:
      - "*"

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml
  build-and-push:
    needs:
      - lint
      - test
    name: Build and Push Docker Image to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
          file: ./Dockerfile
          builder: default
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/pod-notifier:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/pod-notifier:latest
          platforms: linux/amd64,linux/arm64