name: Build and Push Docker Image

on:
  workflow_run:
    workflows: [ "Bump Version and Update Release" ]
    types:
      - completed
  push:
    tags:
      - "*"

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml
  build-and-push:
    name: Build and Push Docker Image to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-tags: 'true'
          fetch-depth: '1'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: 'docker-container'
          install: 'true'
          platforms: linux/amd64,linux/arm64

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-
      - name: Get latest tag
        id: tag
        run: |
          TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
          file: ./Dockerfile
          builder: default
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/pod-notifier:${{ env.TAG }}
            ghcr.io/${{ github.repository_owner }}/pod-notifier:latest
          platforms: linux/amd64,linux/arm64